name: deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
          PORT: ${{ secrets.SSH_PORT }}
          script: |
            # Stop running container
            docker stop backend

            # Remove old container
            docker rm backend

            # Login to Github Container Registry
            docker login https://ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.CR_PAT }}

            # Pull the Docker Image 
            docker pull ghcr.io/${{ github.repository_owner }}/backend:latest

            # Run Container
            docker run -d --restart always --env PORT=${{ secrets.PORT }} --env DATABASE_URL=${{ secrets.DATABASE_URL }} -p 9000:${{ secrets.PORT }} --name "backend" ghcr.io/${{ github.repository_owner }}/backend:latest
      