name: deploy

on:
  workflow_run:
    workflows: ["build"]
    branches: [main]
    types:
      - completed

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
          PORT: ${{ secrets.SSH_PORT }}
          script: |
            # Stop running container
            docker stop ${{ github.repository_owner }}

            # Remove old container
            docker rm ${{ github.repository_owner }}

            # Login to Github Container Registry
            docker login https://ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.CR_PAT }}

            # Pull the Docker Image 
            docker pull ghcr.io/${{ github.repository }}:latest

            # Run a new container from a new image
            docker run -d \
            --restart always \
            --env PORT=${{ secrets.PORT }} \
            --env DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -p 9000:3001 \
            --name $(echo $${{ github.repository }})
